# Generated by Django 2.2.1 on 2019-05-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=6, verbose_name='股票代码')),
                ('abbr', models.CharField(max_length=200, verbose_name='股票简称')),
            ],
            options={
                'verbose_name': 'A股',
                'verbose_name_plural': 'A股',
            },
        ),
        migrations.CreateModel(
            name='AShareDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('price_open', models.FloatField(verbose_name='开盘价')),
                ('price_close', models.FloatField(verbose_name='收盘价')),
                ('price_avg', models.FloatField(verbose_name='平均价')),
                ('rise_rate', models.FloatField(verbose_name='涨跌幅')),
                ('rise_amt', models.FloatField(verbose_name='涨跌额')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashare.AShare')),
            ],
            options={
                'verbose_name': 'A股每日',
                'verbose_name_plural': 'A股每日',
            },
        ),
    ]
