# Generated by Django 2.2.1 on 2019-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashare',
            name='no',
            field=models.CharField(max_length=6, unique=True, verbose_name='股票代码'),
        ),
    ]
