# Generated by Django 2.2.1 on 2019-05-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0002_auto_20190519_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ashare',
            options={'ordering': ['no'], 'verbose_name': 'A股', 'verbose_name_plural': 'A股'},
        ),
        migrations.AddField(
            model_name='asharedaily',
            name='price_lower',
            field=models.FloatField(default=0.0, verbose_name='最低价'),
        ),
        migrations.AddField(
            model_name='asharedaily',
            name='price_upper',
            field=models.FloatField(default=0.0, verbose_name='最高价'),
        ),
        migrations.AlterUniqueTogether(
            name='asharedaily',
            unique_together={('stock', 'date')},
        ),
        migrations.RemoveField(
            model_name='asharedaily',
            name='price_avg',
        ),
    ]
