# Generated by Django 2.2.1 on 2019-05-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0003_auto_20190519_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asharedaily',
            old_name='date',
            new_name='today',
        ),
        migrations.AlterUniqueTogether(
            name='asharedaily',
            unique_together={('stock', 'today')},
        ),
    ]
