# Generated by Django 2.0 on 2019-05-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0004_auto_20190519_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asharedaily',
            options={'ordering': ['-rise_rate'], 'verbose_name': 'A股每日', 'verbose_name_plural': 'A股每日'},
        ),
        migrations.AddField(
            model_name='ashare',
            name='industry',
            field=models.CharField(default='', max_length=200, verbose_name='行业分类'),
        ),
    ]
